### ISSUE TITLE
请问一下这个没有初始化数据库表的脚本吗

### ISSUE THREAD

**Issue by iouAkira** [cashwarden/core-api#8]
你好，请问一下这个没有初始化数据库表的脚本吗，服务起来该怎么初始化数据库呢

**Comment by forecho** [comment]
@iouAkira 是有的，文档遗漏了，我现在补充。

**Comment by forecho** [comment]
https://github.com/cashwarden/core-api/commit/37edec479ea3d98e5035825c54193bcdd8c5d978
